services:

  db:
    image: mysql:9.0
    restart: always
    environment:
      MYSQL_DATABASE: 'yliad_db'
      MYSQL_ROOT_PASSWORD: 'isamovingon'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./run/mysql_db:/var/lib/mysql
